name: 'Deploy to Azure API Management'
description: 'This GitHub Action allows you to update your Azure API Management api from an OpenAPI endpoint or file.'
author: 'Solidify'
inputs:
  swaggerUrl:
    required: true
    description: 'URL to Swagger'
  apiManagementEndpointUrl:
    required: true
    description: 'APIM endpoint URL'
  creds:
    required: true
    description: 'APIM credentials'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: book-open
  color: black
